### ISSUE TITLE
Use the same database across deployments

### ISSUE THREAD

**Issue by igbanam** [zhishi-project/zhishi-backend#121]
I noticed we are using `pg` in production but still using `sqlite3` in development. I do not see anything wrong with using SQLite in development, but I think it would be best to closely mock the production environment in development. This should make deployments easier. 

What are the reasons we decided to choose SQLite for development and PG for production? I guess understanding this may throw more light on this issue

**Comment by innocentamadi** [comment]
I agree with closely mocking production. Especially as we’re having all the issues we have with setting up locally.

@oreoluwa might you have any push-backs on this?

**Comment by andela-oakinniranye** [comment]
I don't really have anything against having the same db across environment. We chose this approach in order to enforce a culture/attitude of writing RDBMS-agnostic queries, the belief being that if it works with pg, and sqlite, it would work with mysql. I see so much value in that, being an OS application, that we believe other orgs may want to clone, we shouldn't really force them to use pg, if they have mysql specialists.

**Comment by igbanam** [comment]
There are some functionalities that other databases do not support. Like search, for example. I think PG is a better database to bank searching on compared to SQLite. Would we want to mitigate the app's capabilities to gain versatility? It's a trade-off discussion.
